name: MarketplaceLendingRevolution
favicon: null
layout_spectrum: 0.99297
typography_spectrum: 0.688142164144665
title: 'Marketplace Lending Revolution - "To borrow is human, to lend divine"'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72802533-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#530011'
    - '#96595b'
    - '#d9b074'
    - '#ff3648'
    - '#b0bef6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
