name: MarketplaceLendingRevolution
favicon: null
layout_spectrum: 0.99297
typography_spectrum: 0.688142164144665
title: 'Marketplace Lending Revolution - "To borrow is human, to lend divine"'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4347676581237465
  lightness: 0.44107209565117955
  saturation: 0.803501004120335
  rhythmicContrast: 0.429403442889452
purpose: []
